# -*- coding: utf-8 -*-
"""음주와흡연.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvMEm9HR-EBtyRktUb_aw_RxmZ14CT4-
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

sm_driking = pd.read_csv('smoking_driking_dataset_Ver01.csv')

king = sm_driking.dropna(axis=0)
king.info()

for column in king.columns:
    unique_values = king[column].unique()
    print(f"'{column}'의 종류 : {unique_values}")

replace_dict = {
    'Male':1, 'Female':0,
    'Y':1, 'N':0
}

king_replaced = king.replace(replace_dict)
king_replaced.info()

data = king_replaced.drop(columns=["DRK_YN"]).to_numpy()
aa=  king_replaced.drop(columns=["DRK_YN"])
target = king_replaced[["DRK_YN"]].to_numpy()

print("Data shape:", data.shape)
print("Target shape:", target.shape)

train_input, test_input, train_target, test_target = train_test_split(
    data, target, random_state=42)
print(train_input.shape, test_input.shape)

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

train_scaled = ss.fit_transform(train_input)
test_scaled = ss.fit_transform(test_input)

from sklearn.tree import DecisionTreeClassifier
# 결정트리 생성 및 학습
dt = DecisionTreeClassifier(random_state=42, max_depth=5)
dt.fit(train_scaled, train_target)

print(dt.score(train_scaled, train_target))
print(dt.score(test_scaled, test_target))

import matplotlib.pyplot as plt
from sklearn.tree import plot_tree

plt.figure(figsize=(15,10))
plot_tree(dt,filled=True)
plt.show()

importance_scores = dt.feature_importances_
column_names = aa.columns.tolist()

for feature, importance in zip(column_names, importance_scores):
    print(f"{feature}: {importance}")